version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fantasy_draft_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fantasy_draft_db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=True
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - .env:/app/.env

volumes:
  postgres_data: